// Action declarations for manage_effect — the server's contract: which params
// each action reads, and which are required. Fleet-authored from handler
// source (three-witness cross-check, 2026-07-04), hand-maintained since:
// adding an action = adding its declaration here (the boot validation and
// tests/schema/action-decl-lint.ps1 enforce both directions).
// UnverifiedDecl = no reachable read path was attributable; validation skips
// those actions and the lint nags until someone verifies or removes them.
#pragma once

#include "MCP/McpCallRegistry.h"

namespace McpDecls
{
inline const FMcpParamDecl P_ManageEffect_2[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("reset"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_3[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("acceleration"), EMcpParamKind::Any, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_4[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("parameterName"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("numBands"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_5[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("cameraOffset"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("offset"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_6[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("collisionMode"), EMcpParamKind::String, false }, { TEXT("restitution"), EMcpParamKind::Number, false }, { TEXT("friction"), EMcpParamKind::Number, false }, { TEXT("dieOnCollision"), EMcpParamKind::Bool, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_7[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("parameterName"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("traceChannel"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_8[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("color"), EMcpParamKind::Object, false }, { TEXT("colorMode"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("startColor"), EMcpParamKind::Array, false }, { TEXT("endColor"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageEffect_9[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, true }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_10[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("eventName"), EMcpParamKind::String, true }, { TEXT("eventType"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("maxEventsPerFrame"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_11[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("eventName"), EMcpParamKind::String, true }, { TEXT("spawnOnEvent"), EMcpParamKind::Bool, false }, { TEXT("eventSpawnCount"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("sourceEventName"), EMcpParamKind::String, false }, { TEXT("sourceEmitterName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_12[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("forceType"), EMcpParamKind::String, false }, { TEXT("forceStrength"), EMcpParamKind::Number, false }, { TEXT("forceVector"), EMcpParamKind::Object, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("force"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageEffect_13[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("lifetime"), EMcpParamKind::Number, false }, { TEXT("mass"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_14[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("killCondition"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_15[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("lightRadius"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("lightIntensity"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_16[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("meshPath"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_18[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("killOnLifetime"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_19[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("materialPath"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("ribbonWidth"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_20[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("stageName"), EMcpParamKind::String, true }, { TEXT("stageIterationSource"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("numIterations"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_21[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("sizeMode"), EMcpParamKind::String, false }, { TEXT("uniformSize"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("sizeScale"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_22[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("parameterName"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_23[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("burstCount"), EMcpParamKind::Number, false }, { TEXT("burstTime"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("burstInterval"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_24[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("spawnPerUnit"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_25[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("spawnRate"), EMcpParamKind::Number, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_26[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("parameterName"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_27[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("materialPath"), EMcpParamKind::String, false }, { TEXT("alignment"), EMcpParamKind::String, false }, { TEXT("facingMode"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_28[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("staticMeshPath"), EMcpParamKind::String, false }, { TEXT("parameterName"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_29[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("parameterName"), EMcpParamKind::String, true }, { TEXT("parameterType"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_30[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("velocity"), EMcpParamKind::Object, false }, { TEXT("velocityMode"), EMcpParamKind::String, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_31[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false }, { TEXT("deltaTime"), EMcpParamKind::Number, false }, { TEXT("steps"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_33[] = { { TEXT("filter"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_35[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("eventName"), EMcpParamKind::String, true }, { TEXT("eventPayload"), EMcpParamKind::Array, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("payloadVariables"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageEffect_37[] = { { TEXT("location"), EMcpParamKind::Any, true }, { TEXT("lightName"), EMcpParamKind::String, false }, { TEXT("lightType"), EMcpParamKind::String, false }, { TEXT("intensity"), EMcpParamKind::Number, false }, { TEXT("color"), EMcpParamKind::Any, false }, { TEXT("pulse"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageEffect_38[] = { { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("location"), EMcpParamKind::Any, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_39[] = { { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("location"), EMcpParamKind::Any, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_40[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, false }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_41[] = { { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("start"), EMcpParamKind::Object, false }, { TEXT("end"), EMcpParamKind::Object, false }, { TEXT("width"), EMcpParamKind::Number, false }, { TEXT("color"), EMcpParamKind::Any, false }, { TEXT("location"), EMcpParamKind::Any, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_42[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, false }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("parameterName"), EMcpParamKind::String, true }, { TEXT("parameterType"), EMcpParamKind::String, false }, { TEXT("value"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_ManageEffect_43[] = { { TEXT("systemPath"), EMcpParamKind::String, false }, { TEXT("emitter"), EMcpParamKind::String, false }, { TEXT("location"), EMcpParamKind::Array, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_44[] = { { TEXT("location"), EMcpParamKind::Array, false }, { TEXT("density"), EMcpParamKind::Number, false }, { TEXT("scattering"), EMcpParamKind::Number, false }, { TEXT("extinction"), EMcpParamKind::Number, false }, { TEXT("name"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_46[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_47[] = { { TEXT("shapeType"), EMcpParamKind::String, false }, { TEXT("shape"), EMcpParamKind::String, false }, { TEXT("location"), EMcpParamKind::Any, true }, { TEXT("duration"), EMcpParamKind::Number, false }, { TEXT("radius"), EMcpParamKind::Number, false }, { TEXT("size"), EMcpParamKind::Number, false }, { TEXT("thickness"), EMcpParamKind::Number, false }, { TEXT("color"), EMcpParamKind::Array, false }, { TEXT("endLocation"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_ManageEffect_48[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("fixedBoundsEnabled"), EMcpParamKind::Bool, false }, { TEXT("deterministicEnabled"), EMcpParamKind::Bool, false }, { TEXT("moduleName"), EMcpParamKind::String, false }, { TEXT("enabled"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_49[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, false }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_52[] = { { TEXT("preset"), EMcpParamKind::String, true }, { TEXT("location"), EMcpParamKind::Any, false }, { TEXT("rotation"), EMcpParamKind::Array, false }, { TEXT("scale"), EMcpParamKind::Any, false }, { TEXT("autoDestroy"), EMcpParamKind::Bool, false }, { TEXT("duration"), EMcpParamKind::Number, false }, { TEXT("size"), EMcpParamKind::Number, false }, { TEXT("thickness"), EMcpParamKind::Number, false }, { TEXT("color"), EMcpParamKind::Array, false }, { TEXT("shapeType"), EMcpParamKind::String, false }, { TEXT("boxSize"), EMcpParamKind::Array, false }, { TEXT("endLocation"), EMcpParamKind::Any, false }, { TEXT("direction"), EMcpParamKind::Any, false }, { TEXT("length"), EMcpParamKind::Number, false }, { TEXT("angle"), EMcpParamKind::Number, false }, { TEXT("halfHeight"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageEffect_54[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("emitterProperties"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageEffect_55[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("parameterName"), EMcpParamKind::String, true }, { TEXT("parameterType"), EMcpParamKind::String, false }, { TEXT("value"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_ManageEffect_56[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("parameterName"), EMcpParamKind::String, true }, { TEXT("parameterValue"), EMcpParamKind::Any, false }, { TEXT("moduleName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_57[] = { { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("location"), EMcpParamKind::Any, false }, { TEXT("rotation"), EMcpParamKind::Array, false }, { TEXT("scale"), EMcpParamKind::Any, false }, { TEXT("autoDestroy"), EMcpParamKind::Bool, false }, { TEXT("attachToActor"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_58[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };

inline const FMcpParamDecl P_ManageEffect_D0[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("reset"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_D1[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("reset"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageEffect_D2[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("scriptType"), EMcpParamKind::String, false }, { TEXT("modulePath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_D3[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("systemPath"), EMcpParamKind::String, true }, { TEXT("emitterPath"), EMcpParamKind::String, false }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("parameterName"), EMcpParamKind::String, true }, { TEXT("sourceBinding"), EMcpParamKind::String, true }, { TEXT("parameterType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_D4[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("scriptType"), EMcpParamKind::String, false }, { TEXT("autoConnect"), EMcpParamKind::Bool, false }, { TEXT("sourceNodeId"), EMcpParamKind::String, false }, { TEXT("sourcePinName"), EMcpParamKind::String, false }, { TEXT("targetNodeId"), EMcpParamKind::String, false }, { TEXT("targetPinName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_D5[] = { { TEXT("systemName"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageEffect_D6[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("scriptType"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, false } };

inline const FMcpCallDecl GManageEffect[] =
{
	{ TEXT("manage_effect"), TEXT("activate"), P_ManageEffect_D0, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("activate_effect"), P_ManageEffect_D1, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("activate_niagara"), P_ManageEffect_2, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_acceleration_module"), P_ManageEffect_3, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_audio_spectrum_data_interface"), P_ManageEffect_4, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_camera_offset_module"), P_ManageEffect_5, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_collision_module"), P_ManageEffect_6, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_collision_query_data_interface"), P_ManageEffect_7, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_color_module"), P_ManageEffect_8, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_emitter_to_system"), P_ManageEffect_9, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_event_generator"), P_ManageEffect_10, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_event_receiver"), P_ManageEffect_11, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_force_module"), P_ManageEffect_12, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_initialize_particle_module"), P_ManageEffect_13, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_kill_particles_module"), P_ManageEffect_14, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_light_renderer_module"), P_ManageEffect_15, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_mesh_renderer_module"), P_ManageEffect_16, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_niagara_module"), P_ManageEffect_D2, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_particle_state_module"), P_ManageEffect_18, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_ribbon_renderer_module"), P_ManageEffect_19, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_simulation_stage"), P_ManageEffect_20, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_size_module"), P_ManageEffect_21, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_skeletal_mesh_data_interface"), P_ManageEffect_22, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_spawn_burst_module"), P_ManageEffect_23, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_spawn_per_unit_module"), P_ManageEffect_24, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_spawn_rate_module"), P_ManageEffect_25, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_spline_data_interface"), P_ManageEffect_26, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_sprite_renderer_module"), P_ManageEffect_27, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_static_mesh_data_interface"), P_ManageEffect_28, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_user_parameter"), P_ManageEffect_29, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("add_velocity_module"), P_ManageEffect_30, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("advance_simulation"), P_ManageEffect_31, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("bind_parameter_to_source"), P_ManageEffect_D3, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("cleanup"), P_ManageEffect_33, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("clear_debug_shapes"), {}, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("configure_event_payload"), P_ManageEffect_35, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("connect_niagara_pins"), P_ManageEffect_D4, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_dynamic_light"), P_ManageEffect_37, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_environment_effect"), P_ManageEffect_38, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_impact_effect"), P_ManageEffect_39, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_niagara_emitter"), P_ManageEffect_40, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_niagara_ribbon"), P_ManageEffect_41, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_niagara_system"), P_ManageEffect_42, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_particle_trail"), P_ManageEffect_43, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("create_volumetric_fog"), P_ManageEffect_44, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("deactivate"), P_ManageEffect_D5, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("deactivate_niagara"), P_ManageEffect_46, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("debug_shape"), P_ManageEffect_47, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("enable_gpu_simulation"), P_ManageEffect_48, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("get_niagara_info"), P_ManageEffect_49, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("list_debug_shapes"), {}, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("particle"), P_ManageEffect_52, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("remove_niagara_node"), P_ManageEffect_D6, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("set_emitter_properties"), P_ManageEffect_54, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("set_niagara_parameter"), P_ManageEffect_55, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("set_parameter_value"), P_ManageEffect_56, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("spawn_niagara"), P_ManageEffect_57, EMcpCallFlags::None },
	{ TEXT("manage_effect"), TEXT("validate_niagara_system"), P_ManageEffect_58, EMcpCallFlags::None },
};
}
