// Action declarations for manage_blueprint — the server's contract: which params
// each action reads, and which are required. Fleet-authored from handler
// source (three-witness cross-check, 2026-07-04), hand-maintained since:
// adding an action = adding its declaration here (the boot validation and
// tests/schema/action-decl-lint.ps1 enforce both directions).
// UnverifiedDecl = no reachable read path was attributable; validation skips
// those actions and the lint nags until someone verifies or removes them.
#pragma once

#include "MCP/McpCallRegistry.h"

namespace McpDecls
{
inline const FMcpParamDecl P_ManageBlueprint_0[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("parentName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_1[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, true }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("value"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_2[] = { { TEXT("sequencePath"), EMcpParamKind::String, true }, { TEXT("bindingGuid"), EMcpParamKind::String, true }, { TEXT("animSequencePath"), EMcpParamKind::String, true }, { TEXT("startTime"), EMcpParamKind::Number, false }, { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("propertyName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_3[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("brushColor"), EMcpParamKind::Object, false }, { TEXT("contentColorAndOpacity"), EMcpParamKind::Object, false }, { TEXT("padding"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageBlueprint_4[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("isEnabled"), EMcpParamKind::Bool, false }, { TEXT("colorAndOpacity"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageBlueprint_5[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_6[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("isChecked"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_7[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("options"), EMcpParamKind::Array, false }, { TEXT("selectedOption"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_8[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("styleClass"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_9[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("buttonClass"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("styleClass"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_10[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("text"), EMcpParamKind::String, false }, { TEXT("styleClass"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_11[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_12[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("componentType"), EMcpParamKind::String, false }, { TEXT("componentName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_13[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageBlueprint_14[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("parentName"), EMcpParamKind::String, false }, { TEXT("size"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_15[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_16[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("eventType"), EMcpParamKind::String, false }, { TEXT("customEventName"), EMcpParamKind::String, false }, { TEXT("eventName"), EMcpParamKind::String, false }, { TEXT("parameters"), EMcpParamKind::Array, false }, { TEXT("posX"), EMcpParamKind::Number, false }, { TEXT("posY"), EMcpParamKind::Number, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("x"), EMcpParamKind::Number, false }, { TEXT("y"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_17[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("functionName"), EMcpParamKind::String, false }, { TEXT("memberName"), EMcpParamKind::String, false }, { TEXT("inputs"), EMcpParamKind::Array, false }, { TEXT("outputs"), EMcpParamKind::Array, false }, { TEXT("isPublic"), EMcpParamKind::Bool, false }, { TEXT("override"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_18[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_19[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("parentName"), EMcpParamKind::String, false }, { TEXT("x"), EMcpParamKind::Number, false }, { TEXT("y"), EMcpParamKind::Number, false }, { TEXT("width"), EMcpParamKind::Number, false }, { TEXT("height"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_20[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_21[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("texturePath"), EMcpParamKind::String, false }, { TEXT("colorAndOpacity"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageBlueprint_22[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("text"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_23[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_24[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("size"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_25[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("nodeType"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("functionName"), EMcpParamKind::String, false }, { TEXT("variableName"), EMcpParamKind::String, false }, { TEXT("nodeName"), EMcpParamKind::String, false }, { TEXT("posX"), EMcpParamKind::Number, false }, { TEXT("posY"), EMcpParamKind::Number, false }, { TEXT("memberName"), EMcpParamKind::String, false }, { TEXT("autoConnect"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Any, false }, { TEXT("x"), EMcpParamKind::Any, false }, { TEXT("y"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_ManageBlueprint_26[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_27[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_28[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("percent"), EMcpParamKind::Number, false }, { TEXT("fillColorAndOpacity"), EMcpParamKind::Object, false }, { TEXT("isMarquee"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_29[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_30[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("text"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_31[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_32[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("stretch"), EMcpParamKind::String, false }, { TEXT("userSpecifiedScale"), EMcpParamKind::Number, false }, { TEXT("stretchDirection"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_33[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("orientation"), EMcpParamKind::String, false }, { TEXT("scrollBarVisibility"), EMcpParamKind::String, false }, { TEXT("alwaysShowScrollbar"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_34[] = { { TEXT("blueprint_path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("component_class"), EMcpParamKind::String, false }, { TEXT("componentClass"), EMcpParamKind::String, false }, { TEXT("component_name"), EMcpParamKind::String, false }, { TEXT("componentName"), EMcpParamKind::String, false }, { TEXT("parent_component"), EMcpParamKind::String, false }, { TEXT("parentComponent"), EMcpParamKind::String, false }, { TEXT("mesh_path"), EMcpParamKind::String, false }, { TEXT("meshPath"), EMcpParamKind::String, false }, { TEXT("material_path"), EMcpParamKind::String, false }, { TEXT("materialPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_35[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("widthOverride"), EMcpParamKind::Number, false }, { TEXT("heightOverride"), EMcpParamKind::Number, false }, { TEXT("minDesiredWidth"), EMcpParamKind::Number, false }, { TEXT("minDesiredHeight"), EMcpParamKind::Number, false }, { TEXT("maxDesiredWidth"), EMcpParamKind::Number, false }, { TEXT("maxDesiredHeight"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_36[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("value"), EMcpParamKind::Number, false }, { TEXT("minValue"), EMcpParamKind::Number, false }, { TEXT("maxValue"), EMcpParamKind::Number, false }, { TEXT("stepSize"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_37[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("sizeX"), EMcpParamKind::Number, false }, { TEXT("sizeY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_38[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("value"), EMcpParamKind::Number, false }, { TEXT("minValue"), EMcpParamKind::Number, false }, { TEXT("maxValue"), EMcpParamKind::Number, false }, { TEXT("delta"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_39[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("text"), EMcpParamKind::String, false }, { TEXT("fontSize"), EMcpParamKind::Number, false }, { TEXT("colorAndOpacity"), EMcpParamKind::Object, false }, { TEXT("autoWrap"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_40[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("multiLine"), EMcpParamKind::Bool, false }, { TEXT("hintText"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_41[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_42[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("slotPadding"), EMcpParamKind::Object, false }, { TEXT("minDesiredSlotWidth"), EMcpParamKind::Number, false }, { TEXT("minDesiredSlotHeight"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_43[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("variableName"), EMcpParamKind::String, true }, { TEXT("variableType"), EMcpParamKind::String, false }, { TEXT("defaultValue"), EMcpParamKind::Any, false }, { TEXT("category"), EMcpParamKind::String, false }, { TEXT("isReplicated"), EMcpParamKind::Bool, false }, { TEXT("isPublic"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_44[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_45[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("widgetClass"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, true }, { TEXT("parentSlot"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_46[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("componentType"), EMcpParamKind::String, true }, { TEXT("componentName"), EMcpParamKind::String, false }, { TEXT("parentName"), EMcpParamKind::String, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("sizeX"), EMcpParamKind::Number, false }, { TEXT("sizeY"), EMcpParamKind::Number, false }, { TEXT("text"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_47[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("activeIndex"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_48[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("parentSlot"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("innerSlotPadding"), EMcpParamKind::Object, false }, { TEXT("wrapSize"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_49[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("styleName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_50[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_53[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("eventName"), EMcpParamKind::String, true }, { TEXT("ownerPin"), EMcpParamKind::String, true }, { TEXT("delegateName"), EMcpParamKind::String, true }, { TEXT("handlerEventName"), EMcpParamKind::String, false }, { TEXT("handlerTargetWidget"), EMcpParamKind::String, false }, { TEXT("handlerFunction"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_54[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("stringTableId"), EMcpParamKind::String, true }, { TEXT("stringKey"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_55[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("delegateName"), EMcpParamKind::String, false }, { TEXT("targetFunction"), EMcpParamKind::String, false }, { TEXT("functionName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_56[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("delegateName"), EMcpParamKind::String, false }, { TEXT("targetFunction"), EMcpParamKind::String, false }, { TEXT("functionName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_57[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("delegateName"), EMcpParamKind::String, false }, { TEXT("targetText"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_60[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("propertyName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_61[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageBlueprint_62[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, true }, { TEXT("pinName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_63[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("saveAfterCompile"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_64[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("sourceNodeId"), EMcpParamKind::String, true }, { TEXT("sourcePinName"), EMcpParamKind::String, true }, { TEXT("targetNodeId"), EMcpParamKind::String, true }, { TEXT("targetPinName"), EMcpParamKind::String, true }, { TEXT("emitterName"), EMcpParamKind::String, false }, { TEXT("scriptType"), EMcpParamKind::String, false }, { TEXT("autoConnect"), EMcpParamKind::Bool, false }, { TEXT("inputName"), EMcpParamKind::String, false }, { TEXT("fromExpression"), EMcpParamKind::Any, false }, { TEXT("toExpression"), EMcpParamKind::Any, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("sourceNodeGuid"), EMcpParamKind::String, true }, { TEXT("targetNodeGuid"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_67[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_68[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_69[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_70[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_71[] = { { TEXT("widgetPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_72[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false }, { TEXT("columns"), EMcpParamKind::Number, false }, { TEXT("rows"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_73[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_74[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("title"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_75[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeType"), EMcpParamKind::String, true }, { TEXT("x"), EMcpParamKind::Number, false }, { TEXT("posX"), EMcpParamKind::Number, false }, { TEXT("y"), EMcpParamKind::Number, false }, { TEXT("posY"), EMcpParamKind::Number, false }, { TEXT("variableName"), EMcpParamKind::String, false }, { TEXT("memberClass"), EMcpParamKind::String, false }, { TEXT("memberName"), EMcpParamKind::String, false }, { TEXT("eventName"), EMcpParamKind::String, false }, { TEXT("parameters"), EMcpParamKind::Array, false }, { TEXT("targetClass"), EMcpParamKind::String, false }, { TEXT("inputAxisName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_76[] = { { TEXT("widgetPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_78[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false }, { TEXT("segments"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_79[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("x"), EMcpParamKind::Number, false }, { TEXT("posX"), EMcpParamKind::Number, false }, { TEXT("y"), EMcpParamKind::Number, false }, { TEXT("posY"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_80[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_81[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false }, { TEXT("columns"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_82[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false }, { TEXT("parentClass"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_83[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, false }, { TEXT("duration"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_84[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("folder"), EMcpParamKind::String, false }, { TEXT("parentClass"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_85[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("styleName"), EMcpParamKind::String, false }, { TEXT("styleType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_86[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_87[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_88[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("parentClass"), EMcpParamKind::String, false }, { TEXT("createIfMissing"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_89[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("actorName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_90[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_93[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("includePinLinks"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_94[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, true }, { TEXT("expressionIndex"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_95[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, true }, { TEXT("pinName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_96[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageBlueprint_97[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("fromState"), EMcpParamKind::String, false }, { TEXT("toState"), EMcpParamKind::String, false }, { TEXT("transitionName"), EMcpParamKind::String, false }, { TEXT("stateMachine"), EMcpParamKind::String, false }, { TEXT("transitionIndex"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_98[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("propertyNames"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageBlueprint_99[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_100[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_102[] = { { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_103[] = { { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("operations"), EMcpParamKind::Array, true }, { TEXT("compile"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageBlueprint_104[] = { { TEXT("widgetPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_105[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageBlueprint_106[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("eventName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_107[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("functionName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_108[] = { { TEXT("blueprint_path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("component_name"), EMcpParamKind::String, false }, { TEXT("componentName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_109[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("variableName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_110[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_111[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("oldName"), EMcpParamKind::String, true }, { TEXT("newName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_112[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("oldName"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("newName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_113[] = { { TEXT("blueprint_path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("component_name"), EMcpParamKind::String, false }, { TEXT("componentName"), EMcpParamKind::String, false }, { TEXT("new_parent"), EMcpParamKind::String, false }, { TEXT("newParent"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_114[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("newParent"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_115[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("newWidgetClass"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_116[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("alignment"), EMcpParamKind::Object, false }, { TEXT("alignmentX"), EMcpParamKind::Number, false }, { TEXT("alignmentY"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_117[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("anchorMin"), EMcpParamKind::Object, false }, { TEXT("anchorMax"), EMcpParamKind::Object, false }, { TEXT("anchorMinX"), EMcpParamKind::Number, false }, { TEXT("anchorMinY"), EMcpParamKind::Number, false }, { TEXT("anchorMaxX"), EMcpParamKind::Number, false }, { TEXT("anchorMaxY"), EMcpParamKind::Number, false }, { TEXT("preset"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_118[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, true }, { TEXT("loop"), EMcpParamKind::Bool, false }, { TEXT("loopCount"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_119[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("animationName"), EMcpParamKind::String, true }, { TEXT("speed"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_120[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("clipping"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_121[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("widgetName"), EMcpParamKind::String, true }, { TEXT("dataTable"), EMcpParamKind::String, true }, { TEXT("rowName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_122[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("widgetName"), EMcpParamKind::String, true }, { TEXT("styleClass"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_123[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("widgetName"), EMcpParamKind::String, true }, { TEXT("styleClass"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_124[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("propertyName"), EMcpParamKind::String, true }, { TEXT("value"), EMcpParamKind::Any, true } };
inline const FMcpParamDecl P_ManageBlueprint_125[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("font"), EMcpParamKind::String, false }, { TEXT("fontSize"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_126[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("namespace"), EMcpParamKind::String, false }, { TEXT("key"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_127[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("left"), EMcpParamKind::Number, false }, { TEXT("top"), EMcpParamKind::Number, false }, { TEXT("right"), EMcpParamKind::Number, false }, { TEXT("bottom"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_128[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("metadata"), EMcpParamKind::Object, true } };
inline const FMcpParamDecl P_ManageBlueprint_129[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, true }, { TEXT("propertyName"), EMcpParamKind::String, true }, { TEXT("value"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_ManageBlueprint_130[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("padding"), EMcpParamKind::Object, false }, { TEXT("pad"), EMcpParamKind::Number, false }, { TEXT("padLeft"), EMcpParamKind::Number, false }, { TEXT("padTop"), EMcpParamKind::Number, false }, { TEXT("padRight"), EMcpParamKind::Number, false }, { TEXT("padBottom"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_131[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("graphName"), EMcpParamKind::String, false }, { TEXT("nodeId"), EMcpParamKind::String, true }, { TEXT("pinName"), EMcpParamKind::String, true }, { TEXT("value"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_132[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("position"), EMcpParamKind::Object, false }, { TEXT("posX"), EMcpParamKind::Number, false }, { TEXT("posY"), EMcpParamKind::Number, false }, { TEXT("x"), EMcpParamKind::Number, false }, { TEXT("y"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_133[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("translation"), EMcpParamKind::Object, false }, { TEXT("scale"), EMcpParamKind::Object, false }, { TEXT("shear"), EMcpParamKind::Object, false }, { TEXT("angle"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_136[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("size"), EMcpParamKind::Object, false }, { TEXT("x"), EMcpParamKind::Number, false }, { TEXT("y"), EMcpParamKind::Number, false }, { TEXT("fill"), EMcpParamKind::Bool, false }, { TEXT("fillWeight"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_137[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("propertyName"), EMcpParamKind::String, false }, { TEXT("value"), EMcpParamKind::Any, false }, { TEXT("style"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_ManageBlueprint_138[] = { { TEXT("requestedPath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("blueprintCandidates"), EMcpParamKind::Array, false }, { TEXT("candidates"), EMcpParamKind::Array, false }, { TEXT("variableName"), EMcpParamKind::String, true }, { TEXT("metadata"), EMcpParamKind::Object, true } };
inline const FMcpParamDecl P_ManageBlueprint_139[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("visibility"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_140[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("targetWidget"), EMcpParamKind::String, true }, { TEXT("property"), EMcpParamKind::String, true }, { TEXT("functionName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_141[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("parentClass"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageBlueprint_142[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("widgetName"), EMcpParamKind::String, false }, { TEXT("zOrder"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageBlueprint_143[] = { { TEXT("widgetPath"), EMcpParamKind::String, false }, { TEXT("widgetId"), EMcpParamKind::String, false }, { TEXT("message"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageBlueprint_144[] = { { TEXT("widgetPath"), EMcpParamKind::String, true }, { TEXT("panelType"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false } };

inline const FMcpCallDecl GManageBlueprint[] =
{
	{ TEXT("manage_blueprint"), TEXT("add_ammo_counter"), P_ManageBlueprint_0, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_animation_keyframe"), P_ManageBlueprint_1, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_animation_track"), P_ManageBlueprint_2, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_border"), P_ManageBlueprint_3, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_button"), P_ManageBlueprint_4, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_canvas_panel"), P_ManageBlueprint_5, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_check_box"), P_ManageBlueprint_6, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_combo_box"), P_ManageBlueprint_7, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_common_border"), P_ManageBlueprint_8, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_common_button"), P_ManageBlueprint_9, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_common_text"), P_ManageBlueprint_10, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_compass"), P_ManageBlueprint_11, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_component"), P_ManageBlueprint_12, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("add_construction_script"), P_ManageBlueprint_13, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_crosshair"), P_ManageBlueprint_14, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_damage_indicator"), P_ManageBlueprint_15, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_event"), P_ManageBlueprint_16, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_function"), P_ManageBlueprint_17, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_grid_panel"), P_ManageBlueprint_18, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_health_bar"), P_ManageBlueprint_19, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_horizontal_box"), P_ManageBlueprint_20, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_image"), P_ManageBlueprint_21, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_interaction_prompt"), P_ManageBlueprint_22, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_list_view"), P_ManageBlueprint_23, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_minimap"), P_ManageBlueprint_24, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_node"), P_ManageBlueprint_25, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_objective_tracker"), P_ManageBlueprint_26, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_overlay"), P_ManageBlueprint_27, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_progress_bar"), P_ManageBlueprint_28, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_quest_tracker"), P_ManageBlueprint_29, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_rich_text_block"), P_ManageBlueprint_30, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_safe_zone"), P_ManageBlueprint_31, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_scale_box"), P_ManageBlueprint_32, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_scroll_box"), P_ManageBlueprint_33, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_scs_component"), P_ManageBlueprint_34, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_size_box"), P_ManageBlueprint_35, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_slider"), P_ManageBlueprint_36, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_spacer"), P_ManageBlueprint_37, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_spin_box"), P_ManageBlueprint_38, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_text_block"), P_ManageBlueprint_39, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_text_input"), P_ManageBlueprint_40, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_tree_view"), P_ManageBlueprint_41, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_uniform_grid"), P_ManageBlueprint_42, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_variable"), P_ManageBlueprint_43, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_vertical_box"), P_ManageBlueprint_44, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_widget"), P_ManageBlueprint_45, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_widget_component"), P_ManageBlueprint_46, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_widget_switcher"), P_ManageBlueprint_47, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("add_wrap_box"), P_ManageBlueprint_48, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("apply_style_to_widget"), P_ManageBlueprint_49, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("arrange_graph"), P_ManageBlueprint_50, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("bind_color"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("bind_enabled"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("bind_event_to_delegate"), P_ManageBlueprint_53, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("bind_localized_text"), P_ManageBlueprint_54, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("bind_on_clicked"), P_ManageBlueprint_55, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("bind_on_hovered"), P_ManageBlueprint_56, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("bind_on_value_changed"), P_ManageBlueprint_57, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("bind_text"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("bind_visibility"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("blueprint_get_default"), P_ManageBlueprint_60, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("blueprint_list_functions"), P_ManageBlueprint_61, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("break_pin_links"), P_ManageBlueprint_62, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("compile"), P_ManageBlueprint_63, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("connect_pins"), P_ManageBlueprint_64, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("create_blueprint"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("create_common_button_style"), P_ManageBlueprint_67, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_common_text_style"), P_ManageBlueprint_68, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_credits_screen"), P_ManageBlueprint_69, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_dialog_widget"), P_ManageBlueprint_70, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_hud_widget"), P_ManageBlueprint_71, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_inventory_ui"), P_ManageBlueprint_72, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_loading_screen"), P_ManageBlueprint_73, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_main_menu"), P_ManageBlueprint_74, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_node"), P_ManageBlueprint_75, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_pause_menu"), P_ManageBlueprint_76, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_property_binding"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("create_radial_menu"), P_ManageBlueprint_78, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_reroute_node"), P_ManageBlueprint_79, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_settings_menu"), P_ManageBlueprint_80, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_shop_ui"), P_ManageBlueprint_81, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_widget"), P_ManageBlueprint_82, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_widget_animation"), P_ManageBlueprint_83, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_widget_blueprint"), P_ManageBlueprint_84, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("create_widget_style"), P_ManageBlueprint_85, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("delete_animation"), P_ManageBlueprint_86, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("delete_node"), P_ManageBlueprint_87, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("ensure_exists"), P_ManageBlueprint_88, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get"), P_ManageBlueprint_89, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_animation_info"), P_ManageBlueprint_90, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_blueprint"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("get_default"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("get_graph_details"), P_ManageBlueprint_93, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_node_details"), P_ManageBlueprint_94, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_pin_details"), P_ManageBlueprint_95, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_scs"), P_ManageBlueprint_96, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("get_transition_rule_graph"), P_ManageBlueprint_97, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_widget_info"), P_ManageBlueprint_98, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("get_widget_slot_info"), P_ManageBlueprint_99, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("list_animbp_graphs"), P_ManageBlueprint_100, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("list_functions"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("list_node_types"), P_ManageBlueprint_102, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("modify_scs"), P_ManageBlueprint_103, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("preview_widget"), P_ManageBlueprint_104, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("probe_handle"), P_ManageBlueprint_105, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("remove_event"), P_ManageBlueprint_106, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("remove_function"), P_ManageBlueprint_107, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("remove_scs_component"), P_ManageBlueprint_108, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("remove_variable"), P_ManageBlueprint_109, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("remove_widget"), P_ManageBlueprint_110, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("rename_variable"), P_ManageBlueprint_111, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("rename_widget"), P_ManageBlueprint_112, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("reparent_scs_component"), P_ManageBlueprint_113, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("reparent_widget"), P_ManageBlueprint_114, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("replace_widget_class"), P_ManageBlueprint_115, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_alignment"), P_ManageBlueprint_116, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_anchor"), P_ManageBlueprint_117, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_animation_loop"), P_ManageBlueprint_118, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_animation_speed"), P_ManageBlueprint_119, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_clipping"), P_ManageBlueprint_120, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_common_button_input_action"), P_ManageBlueprint_121, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_common_button_style"), P_ManageBlueprint_122, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_common_text_style"), P_ManageBlueprint_123, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_default"), P_ManageBlueprint_124, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_font"), P_ManageBlueprint_125, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_localization_key"), P_ManageBlueprint_126, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_margin"), P_ManageBlueprint_127, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_metadata"), P_ManageBlueprint_128, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_node_property"), P_ManageBlueprint_129, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_padding"), P_ManageBlueprint_130, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_pin_default_value"), P_ManageBlueprint_131, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_position"), P_ManageBlueprint_132, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_render_transform"), P_ManageBlueprint_133, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_scs_property"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("set_scs_transform"), {}, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("set_size"), P_ManageBlueprint_136, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_style"), P_ManageBlueprint_137, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_variable_metadata"), P_ManageBlueprint_138, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_visibility"), P_ManageBlueprint_139, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_widget_binding"), P_ManageBlueprint_140, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_widget_parent_class"), P_ManageBlueprint_141, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("set_z_order"), P_ManageBlueprint_142, EMcpCallFlags::None },
	{ TEXT("manage_blueprint"), TEXT("show_widget"), P_ManageBlueprint_143, EMcpCallFlags::UnverifiedDecl },
	{ TEXT("manage_blueprint"), TEXT("wrap_root"), P_ManageBlueprint_144, EMcpCallFlags::None },
};
}
