// Action declarations for manage_level_structure — the server's contract: which params
// each action reads, and which are required. Fleet-authored from handler
// source (three-witness cross-check, 2026-07-04), hand-maintained since:
// adding an action = adding its declaration here (the boot validation and
// tests/schema/action-decl-lint.ps1 enforce both directions).
// UnverifiedDecl = no reachable read path was attributable; validation skips
// those actions and the lint nags until someone verifies or removes them.
#pragma once

#include "MCP/McpCallRegistry.h"

namespace McpDecls
{
inline const FMcpParamDecl P_ManageLevelStructure_0[] = { { TEXT("actorPath"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_1[] = { { TEXT("actorPath"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("cullDistances"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageLevelStructure_2[] = { { TEXT("actorPath"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("killZHeight"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_3[] = { { TEXT("nodeClass"), EMcpParamKind::String, true }, { TEXT("nodeName"), EMcpParamKind::String, false }, { TEXT("nodePosition"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_4[] = { { TEXT("actorPath"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("bWaterVolume"), EMcpParamKind::Bool, false }, { TEXT("fluidFriction"), EMcpParamKind::Number, false }, { TEXT("terminalVelocity"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_5[] = { { TEXT("actorPath"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("priority"), EMcpParamKind::Number, false }, { TEXT("blendRadius"), EMcpParamKind::Number, false }, { TEXT("blendWeight"), EMcpParamKind::Number, false }, { TEXT("enabled"), EMcpParamKind::Bool, false }, { TEXT("bUnbound"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_6[] = { { TEXT("actorPath"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_7[] = { { TEXT("actorName"), EMcpParamKind::String, true }, { TEXT("dataLayerName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageLevelStructure_8[] = { { TEXT("gridName"), EMcpParamKind::String, false }, { TEXT("gridCellSize"), EMcpParamKind::Number, false }, { TEXT("loadingRange"), EMcpParamKind::Number, false }, { TEXT("bBlockOnSlowStreaming"), EMcpParamKind::Bool, false }, { TEXT("priority"), EMcpParamKind::Number, false }, { TEXT("createIfMissing"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_9[] = { { TEXT("hlodLayerName"), EMcpParamKind::String, true }, { TEXT("hlodLayerPath"), EMcpParamKind::String, false }, { TEXT("bIsSpatiallyLoaded"), EMcpParamKind::Bool, false }, { TEXT("cellSize"), EMcpParamKind::Number, false }, { TEXT("loadingDistance"), EMcpParamKind::Number, false }, { TEXT("layerType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageLevelStructure_10[] = { { TEXT("bAutoCalculateBounds"), EMcpParamKind::Bool, false }, { TEXT("boundsOrigin"), EMcpParamKind::Object, false }, { TEXT("boundsExtent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_11[] = { { TEXT("levelName"), EMcpParamKind::String, true }, { TEXT("streamingMethod"), EMcpParamKind::String, false }, { TEXT("bShouldBeVisible"), EMcpParamKind::Bool, false }, { TEXT("bShouldBlockOnLoad"), EMcpParamKind::Bool, false }, { TEXT("bDisableDistanceStreaming"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_12[] = { { TEXT("sourceNodeName"), EMcpParamKind::String, true }, { TEXT("sourcePinName"), EMcpParamKind::String, false }, { TEXT("targetNodeName"), EMcpParamKind::String, true }, { TEXT("targetPinName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageLevelStructure_13[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("bEnabled"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_14[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_15[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_16[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("cullDistances"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageLevelStructure_17[] = { { TEXT("dataLayerName"), EMcpParamKind::String, true }, { TEXT("dataLayerAssetPath"), EMcpParamKind::String, false }, { TEXT("bIsInitiallyVisible"), EMcpParamKind::Bool, false }, { TEXT("bIsInitiallyLoaded"), EMcpParamKind::Bool, false }, { TEXT("dataLayerType"), EMcpParamKind::String, false }, { TEXT("bIsPrivate"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_18[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_19[] = { { TEXT("levelName"), EMcpParamKind::String, true }, { TEXT("levelPath"), EMcpParamKind::String, false }, { TEXT("bCreateWorldPartition"), EMcpParamKind::Bool, false }, { TEXT("bUseExternalActors"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("loadAfterCreate"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_20[] = { { TEXT("levelInstanceName"), EMcpParamKind::String, false }, { TEXT("levelAssetPath"), EMcpParamKind::String, true }, { TEXT("instanceLocation"), EMcpParamKind::Object, false }, { TEXT("instanceRotation"), EMcpParamKind::Object, false }, { TEXT("instanceScale"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_21[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_22[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_23[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_24[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_25[] = { { TEXT("packedLevelName"), EMcpParamKind::String, false }, { TEXT("levelAssetPath"), EMcpParamKind::String, false }, { TEXT("instanceLocation"), EMcpParamKind::Object, false }, { TEXT("instanceRotation"), EMcpParamKind::Object, false }, { TEXT("bPackBlueprints"), EMcpParamKind::Bool, false }, { TEXT("bPackStaticMeshes"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_26[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("bPainCausing"), EMcpParamKind::Bool, false }, { TEXT("damagePerSec"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_27[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("bWaterVolume"), EMcpParamKind::Bool, false }, { TEXT("fluidFriction"), EMcpParamKind::Number, false }, { TEXT("terminalVelocity"), EMcpParamKind::Number, false }, { TEXT("priority"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_28[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("priority"), EMcpParamKind::Number, false }, { TEXT("blendRadius"), EMcpParamKind::Number, false }, { TEXT("blendWeight"), EMcpParamKind::Number, false }, { TEXT("enabled"), EMcpParamKind::Bool, false }, { TEXT("bUnbound"), EMcpParamKind::Bool, false }, { TEXT("postProcessSettings"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_29[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_30[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("bEnabled"), EMcpParamKind::Bool, false }, { TEXT("reverbVolume"), EMcpParamKind::Number, false }, { TEXT("fadeTime"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_31[] = { { TEXT("sublevelName"), EMcpParamKind::String, true }, { TEXT("sublevelPath"), EMcpParamKind::String, false }, { TEXT("parentLevel"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_32[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("boxExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_33[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("capsuleRadius"), EMcpParamKind::Number, false }, { TEXT("capsuleHalfHeight"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_34[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("sphereRadius"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageLevelStructure_35[] = { { TEXT("volumeName"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_36[] = { { TEXT("bEnableWorldPartition"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_38[] = { { TEXT("path"), EMcpParamKind::String, false }, { TEXT("filter"), EMcpParamKind::String, false }, { TEXT("volumeType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageLevelStructure_40[] = { { TEXT("volumeName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageLevelStructure_41[] = { { TEXT("levelName"), EMcpParamKind::String, true }, { TEXT("streamingDistance"), EMcpParamKind::Number, false }, { TEXT("streamingUsage"), EMcpParamKind::String, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("createVolume"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_ManageLevelStructure_42[] = { { TEXT("volumeName"), EMcpParamKind::String, true }, { TEXT("bounds"), EMcpParamKind::Array, false }, { TEXT("volumeExtent"), EMcpParamKind::Object, false }, { TEXT("extent"), EMcpParamKind::Object, false }, { TEXT("volumeLocation"), EMcpParamKind::Object, false }, { TEXT("location"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_ManageLevelStructure_43[] = { { TEXT("volumeName"), EMcpParamKind::String, true }, { TEXT("volumeExtent"), EMcpParamKind::Object, true }, { TEXT("extent"), EMcpParamKind::Object, true } };
inline const FMcpParamDecl P_ManageLevelStructure_44[] = { { TEXT("volumeName"), EMcpParamKind::String, true }, { TEXT("bWaterVolume"), EMcpParamKind::Bool, false }, { TEXT("fluidFriction"), EMcpParamKind::Number, false }, { TEXT("terminalVelocity"), EMcpParamKind::Number, false }, { TEXT("priority"), EMcpParamKind::Number, false }, { TEXT("bPainCausing"), EMcpParamKind::Bool, false }, { TEXT("damagePerSec"), EMcpParamKind::Number, false }, { TEXT("bEnabled"), EMcpParamKind::Bool, false }, { TEXT("reverbVolume"), EMcpParamKind::Number, false }, { TEXT("fadeTime"), EMcpParamKind::Number, false } };

inline const FMcpCallDecl GManageLevelStructure[] =
{
	{ TEXT("manage_level_structure"), TEXT("add_blocking_volume"), P_ManageLevelStructure_0, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("add_cull_distance_volume"), P_ManageLevelStructure_1, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("add_kill_z_volume"), P_ManageLevelStructure_2, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("add_level_blueprint_node"), P_ManageLevelStructure_3, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("add_physics_volume"), P_ManageLevelStructure_4, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("add_post_process_volume"), P_ManageLevelStructure_5, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("add_trigger_volume"), P_ManageLevelStructure_6, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("assign_actor_to_data_layer"), P_ManageLevelStructure_7, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("configure_grid_size"), P_ManageLevelStructure_8, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("configure_hlod_layer"), P_ManageLevelStructure_9, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("configure_level_bounds"), P_ManageLevelStructure_10, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("configure_level_streaming"), P_ManageLevelStructure_11, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("connect_level_blueprint_nodes"), P_ManageLevelStructure_12, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_audio_volume"), P_ManageLevelStructure_13, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_blocking_volume"), P_ManageLevelStructure_14, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_camera_blocking_volume"), P_ManageLevelStructure_15, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_cull_distance_volume"), P_ManageLevelStructure_16, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_data_layer"), P_ManageLevelStructure_17, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_kill_z_volume"), P_ManageLevelStructure_18, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_level"), P_ManageLevelStructure_19, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_level_instance"), P_ManageLevelStructure_20, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_lightmass_importance_volume"), P_ManageLevelStructure_21, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_minimap_volume"), P_ManageLevelStructure_22, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_nav_mesh_bounds_volume"), P_ManageLevelStructure_23, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_nav_modifier_volume"), P_ManageLevelStructure_24, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_packed_level_actor"), P_ManageLevelStructure_25, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_pain_causing_volume"), P_ManageLevelStructure_26, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_physics_volume"), P_ManageLevelStructure_27, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_post_process_volume"), P_ManageLevelStructure_28, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_precomputed_visibility_volume"), P_ManageLevelStructure_29, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_reverb_volume"), P_ManageLevelStructure_30, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_sublevel"), P_ManageLevelStructure_31, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_trigger_box"), P_ManageLevelStructure_32, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_trigger_capsule"), P_ManageLevelStructure_33, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_trigger_sphere"), P_ManageLevelStructure_34, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("create_trigger_volume"), P_ManageLevelStructure_35, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("enable_world_partition"), P_ManageLevelStructure_36, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("get_level_structure_info"), {}, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("get_volumes_info"), P_ManageLevelStructure_38, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("open_level_blueprint"), {}, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("remove_volume"), P_ManageLevelStructure_40, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("set_streaming_distance"), P_ManageLevelStructure_41, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("set_volume_bounds"), P_ManageLevelStructure_42, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("set_volume_extent"), P_ManageLevelStructure_43, EMcpCallFlags::None },
	{ TEXT("manage_level_structure"), TEXT("set_volume_properties"), P_ManageLevelStructure_44, EMcpCallFlags::None },
};
}
