// Action declarations for animation_physics — the server's contract: which params
// each action reads, and which are required. Fleet-authored from handler
// source (three-witness cross-check, 2026-07-04), hand-maintained since:
// adding an action = adding its declaration here (the boot validation and
// tests/schema/action-decl-lint.ps1 enforce both directions).
// UnverifiedDecl = no reachable read path was attributable; validation skips
// those actions and the lint nags until someone verifies or removes them.
#pragma once

#include "MCP/McpCallRegistry.h"

namespace McpDecls
{
inline const FMcpParamDecl P_AnimationPhysics_0[] = { { TEXT("actorName"), EMcpParamKind::String, true }, { TEXT("activate"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_1[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("animationPath"), EMcpParamKind::String, true }, { TEXT("yaw"), EMcpParamKind::Number, false }, { TEXT("pitch"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_2[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("nodeType"), EMcpParamKind::String, false }, { TEXT("nodeName"), EMcpParamKind::String, false }, { TEXT("blendType"), EMcpParamKind::String, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_3[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("animationPath"), EMcpParamKind::String, true }, { TEXT("sampleX"), EMcpParamKind::Number, false }, { TEXT("sampleY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("sampleValue"), EMcpParamKind::Any, false } };
inline const FMcpParamDecl P_AnimationPhysics_4[] = { { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("parentBone"), EMcpParamKind::String, false }, { TEXT("parentBoneName"), EMcpParamKind::String, false }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("scale"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_AnimationPhysics_5[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_6[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("poseName"), EMcpParamKind::String, false }, { TEXT("cacheName"), EMcpParamKind::String, true }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_7[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_8[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("notifyName"), EMcpParamKind::String, true }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("notifyClass"), EMcpParamKind::String, false }, { TEXT("trackIndex"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_9[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("sectionName"), EMcpParamKind::String, true }, { TEXT("startTime"), EMcpParamKind::Number, false }, { TEXT("montagePath"), EMcpParamKind::String, false }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_10[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("animationPath"), EMcpParamKind::String, true }, { TEXT("startTime"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_11[] = { { TEXT("animationPath"), EMcpParamKind::String, true }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("notifyName"), EMcpParamKind::String, true }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("notifyClass"), EMcpParamKind::String, false }, { TEXT("frame"), EMcpParamKind::Number, false }, { TEXT("trackIndex"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_12[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("notifyClass"), EMcpParamKind::String, false }, { TEXT("startFrame"), EMcpParamKind::Number, false }, { TEXT("endFrame"), EMcpParamKind::Number, false }, { TEXT("trackIndex"), EMcpParamKind::Number, false }, { TEXT("notifyName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_13[] = { { TEXT("physicsAssetPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("bodyType"), EMcpParamKind::String, false }, { TEXT("radius"), EMcpParamKind::Number, false }, { TEXT("length"), EMcpParamKind::Number, false }, { TEXT("width"), EMcpParamKind::Number, false }, { TEXT("height"), EMcpParamKind::Number, false }, { TEXT("depth"), EMcpParamKind::Number, false }, { TEXT("center"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_14[] = { { TEXT("physicsAssetPath"), EMcpParamKind::String, true }, { TEXT("bodyA"), EMcpParamKind::String, true }, { TEXT("bodyB"), EMcpParamKind::String, true }, { TEXT("constraintName"), EMcpParamKind::String, false }, { TEXT("limits"), EMcpParamKind::Object, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_15[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("groupName"), EMcpParamKind::String, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_16[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("stateName"), EMcpParamKind::String, true }, { TEXT("machineName"), EMcpParamKind::String, false }, { TEXT("animationPath"), EMcpParamKind::String, false }, { TEXT("isEntry"), EMcpParamKind::Bool, false }, { TEXT("isExit"), EMcpParamKind::Bool, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("stateMachineName"), EMcpParamKind::String, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_17[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("machineName"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("stateMachineName"), EMcpParamKind::String, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_18[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("markerName"), EMcpParamKind::String, true }, { TEXT("frame"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_19[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("machineName"), EMcpParamKind::String, false }, { TEXT("sourceState"), EMcpParamKind::String, true }, { TEXT("targetState"), EMcpParamKind::String, true }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("stateMachineName"), EMcpParamKind::String, false }, { TEXT("fromState"), EMcpParamKind::String, true }, { TEXT("toState"), EMcpParamKind::String, true }, { TEXT("crossfadeDuration"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_20[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_AnimationPhysics_21[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_AnimationPhysics_22[] = { { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("notifyName"), EMcpParamKind::String, true }, { TEXT("functionName"), EMcpParamKind::String, true }, { TEXT("targetClass"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("positionX"), EMcpParamKind::Number, false }, { TEXT("positionY"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_23[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("clothAssetName"), EMcpParamKind::String, false }, { TEXT("meshLodIndex"), EMcpParamKind::Number, false }, { TEXT("sectionIndex"), EMcpParamKind::Number, false }, { TEXT("assetLodIndex"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_24[] = { { TEXT("artifacts"), EMcpParamKind::Array, true } };
inline const FMcpParamDecl P_AnimationPhysics_25[] = { { TEXT("physicsAssetPath"), EMcpParamKind::String, true }, { TEXT("bodyA"), EMcpParamKind::String, true }, { TEXT("bodyB"), EMcpParamKind::String, true }, { TEXT("limits"), EMcpParamKind::Object, false }, { TEXT("swing1LimitAngle"), EMcpParamKind::Number, false }, { TEXT("swing2LimitAngle"), EMcpParamKind::Number, false }, { TEXT("twistLimitAngle"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_26[] = { { TEXT("physicsAssetPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("mass"), EMcpParamKind::Number, false }, { TEXT("linearDamping"), EMcpParamKind::Number, false }, { TEXT("angularDamping"), EMcpParamKind::Number, false }, { TEXT("collisionEnabled"), EMcpParamKind::Bool, false }, { TEXT("simulatePhysics"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_27[] = { { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("socketName"), EMcpParamKind::String, true }, { TEXT("attachBoneName"), EMcpParamKind::String, false }, { TEXT("relativeLocation"), EMcpParamKind::Object, false }, { TEXT("relativeRotation"), EMcpParamKind::Object, false }, { TEXT("relativeScale"), EMcpParamKind::Object, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_28[] = { { TEXT("actorName"), EMcpParamKind::String, false }, { TEXT("vehicleName"), EMcpParamKind::String, false }, { TEXT("vehicleType"), EMcpParamKind::String, false }, { TEXT("wheels"), EMcpParamKind::Array, false }, { TEXT("engine"), EMcpParamKind::Object, false }, { TEXT("transmission"), EMcpParamKind::Object, false }, { TEXT("mass"), EMcpParamKind::Number, false }, { TEXT("dragCoefficient"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_29[] = { { TEXT("sourceMeshPath"), EMcpParamKind::String, true }, { TEXT("targetMeshPath"), EMcpParamKind::String, true }, { TEXT("profileName"), EMcpParamKind::String, false }, { TEXT("lodIndex"), EMcpParamKind::Number, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_30[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("is1D"), EMcpParamKind::Bool, false }, { TEXT("minX"), EMcpParamKind::Number, false }, { TEXT("maxX"), EMcpParamKind::Number, false }, { TEXT("gridX"), EMcpParamKind::Number, false }, { TEXT("minY"), EMcpParamKind::Number, false }, { TEXT("maxY"), EMcpParamKind::Number, false }, { TEXT("gridY"), EMcpParamKind::Number, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_31[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("meshPath"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("parentClass"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_32[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("assetType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_35[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("sequenceName"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("frameRate"), EMcpParamKind::Number, false }, { TEXT("numFrames"), EMcpParamKind::Number, false }, { TEXT("length"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_36[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("dimensions"), EMcpParamKind::Number, false }, { TEXT("minX"), EMcpParamKind::Number, false }, { TEXT("maxX"), EMcpParamKind::Number, false }, { TEXT("gridX"), EMcpParamKind::Number, false }, { TEXT("minY"), EMcpParamKind::Number, false }, { TEXT("maxY"), EMcpParamKind::Number, false }, { TEXT("gridY"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_37[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("minX"), EMcpParamKind::Number, false }, { TEXT("maxX"), EMcpParamKind::Number, false }, { TEXT("gridX"), EMcpParamKind::Number, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("axisName"), EMcpParamKind::String, false }, { TEXT("axisMin"), EMcpParamKind::Number, false }, { TEXT("axisMax"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_38[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("minX"), EMcpParamKind::Number, false }, { TEXT("maxX"), EMcpParamKind::Number, false }, { TEXT("gridX"), EMcpParamKind::Number, false }, { TEXT("minY"), EMcpParamKind::Number, false }, { TEXT("maxY"), EMcpParamKind::Number, false }, { TEXT("gridY"), EMcpParamKind::Number, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("horizontalAxisName"), EMcpParamKind::String, false }, { TEXT("horizontalMin"), EMcpParamKind::Number, false }, { TEXT("horizontalMax"), EMcpParamKind::Number, false }, { TEXT("verticalAxisName"), EMcpParamKind::String, false }, { TEXT("verticalMin"), EMcpParamKind::Number, false }, { TEXT("verticalMax"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_39[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("treeName"), EMcpParamKind::String, false }, { TEXT("blendParameters"), EMcpParamKind::Array, false }, { TEXT("children"), EMcpParamKind::Array, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_40[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("modularRig"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_41[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("sourceIKRigPath"), EMcpParamKind::String, false }, { TEXT("targetIKRigPath"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_42[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("meshPath"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_43[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("montageName"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("slotName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("length"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_44[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("morphTargetName"), EMcpParamKind::String, true }, { TEXT("deltas"), EMcpParamKind::Array, true }, { TEXT("lodIndex"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_45[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("outputPath"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_46[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("directory"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_47[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("boneTracks"), EMcpParamKind::Array, true }, { TEXT("numFrames"), EMcpParamKind::Number, false }, { TEXT("frameRate"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_48[] = { { TEXT("path"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("rootBoneName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_49[] = { { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("socketName"), EMcpParamKind::String, true }, { TEXT("attachBoneName"), EMcpParamKind::String, false }, { TEXT("boneName"), EMcpParamKind::String, false }, { TEXT("relativeLocation"), EMcpParamKind::Object, false }, { TEXT("relativeRotation"), EMcpParamKind::Object, false }, { TEXT("relativeScale"), EMcpParamKind::Object, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_50[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("name"), EMcpParamKind::String, false }, { TEXT("machineName"), EMcpParamKind::String, false }, { TEXT("states"), EMcpParamKind::Array, false }, { TEXT("transitions"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_AnimationPhysics_51[] = { { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("sourceBoneName"), EMcpParamKind::String, true }, { TEXT("targetBoneName"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_52[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("rebuildBlendParameters"), EMcpParamKind::Bool, false }, { TEXT("compileReferencers"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_53[] = { { TEXT("assetPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_AnimationPhysics_54[] = { { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_55[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("morphTargetPath"), EMcpParamKind::String, false }, { TEXT("sourcePath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_56[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("fromSection"), EMcpParamKind::String, true }, { TEXT("toSection"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_57[] = { { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_58[] = { { TEXT("physicsAssetPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_59[] = { { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_60[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("axis"), EMcpParamKind::String, false }, { TEXT("profileName"), EMcpParamKind::String, false }, { TEXT("lodIndex"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_61[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_AnimationPhysics_63[] = { { TEXT("actorName"), EMcpParamKind::String, true }, { TEXT("montagePath"), EMcpParamKind::String, true }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("playRate"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_64[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("threshold"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_65[] = { { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("removeChildren"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_66[] = { { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("newBoneName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_67[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("additiveAnimType"), EMcpParamKind::String, false }, { TEXT("basePoseType"), EMcpParamKind::String, false }, { TEXT("basePoseAnimation"), EMcpParamKind::String, false }, { TEXT("basePoseFrame"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_68[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("nodeName"), EMcpParamKind::String, true }, { TEXT("propertyName"), EMcpParamKind::String, true }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("value"), EMcpParamKind::Any, true } };
inline const FMcpParamDecl P_AnimationPhysics_69[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("axisIndex"), EMcpParamKind::Number, false }, { TEXT("minValue"), EMcpParamKind::Number, false }, { TEXT("maxValue"), EMcpParamKind::Number, false }, { TEXT("gridNum"), EMcpParamKind::Number, false }, { TEXT("axisName"), EMcpParamKind::String, false }, { TEXT("axis"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("gridDivisions"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_70[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blendTime"), EMcpParamKind::Number, false }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("blendOption"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_71[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("blendTime"), EMcpParamKind::Number, false }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("blendOption"), EMcpParamKind::String, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_72[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("position"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("scale"), EMcpParamKind::Object, false }, { TEXT("frame"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false }, { TEXT("location"), EMcpParamKind::Object, false } };
inline const FMcpParamDecl P_AnimationPhysics_73[] = { { TEXT("skeletonPath"), EMcpParamKind::String, true }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("parentBone"), EMcpParamKind::String, false }, { TEXT("newParentBone"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_74[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("boneName"), EMcpParamKind::String, true }, { TEXT("location"), EMcpParamKind::Object, false }, { TEXT("rotation"), EMcpParamKind::Object, false }, { TEXT("scale"), EMcpParamKind::Object, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_75[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("curveName"), EMcpParamKind::String, true }, { TEXT("time"), EMcpParamKind::Number, false }, { TEXT("value"), EMcpParamKind::Number, false }, { TEXT("frame"), EMcpParamKind::Number, false }, { TEXT("createIfMissing"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_76[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("interpolationSpeed"), EMcpParamKind::Number, false }, { TEXT("interpolationType"), EMcpParamKind::String, false }, { TEXT("targetWeightInterpolationSpeed"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_77[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("morphTargetName"), EMcpParamKind::String, true }, { TEXT("deltas"), EMcpParamKind::Array, true }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_78[] = { { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("sourceChain"), EMcpParamKind::String, true }, { TEXT("targetChain"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_AnimationPhysics_79[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("enableRootMotion"), EMcpParamKind::Bool, false }, { TEXT("rootMotionRootLock"), EMcpParamKind::String, false }, { TEXT("forceRootLock"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_80[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("sectionName"), EMcpParamKind::String, true }, { TEXT("startTime"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_81[] = { { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("length"), EMcpParamKind::Number, true }, { TEXT("frameRate"), EMcpParamKind::Number, false }, { TEXT("numFrames"), EMcpParamKind::Number, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_82[] = { { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("machineName"), EMcpParamKind::String, false }, { TEXT("sourceState"), EMcpParamKind::String, true }, { TEXT("targetState"), EMcpParamKind::String, true }, { TEXT("condition"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("stateMachineName"), EMcpParamKind::String, false }, { TEXT("fromState"), EMcpParamKind::String, false }, { TEXT("toState"), EMcpParamKind::String, false }, { TEXT("crossfadeDuration"), EMcpParamKind::Number, false }, { TEXT("priorityOrder"), EMcpParamKind::Number, false }, { TEXT("automaticRule"), EMcpParamKind::Bool, false }, { TEXT("bidirectional"), EMcpParamKind::Bool, false }, { TEXT("save"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_83[] = { { TEXT("skeletalMeshPath"), EMcpParamKind::String, true }, { TEXT("profileName"), EMcpParamKind::String, false }, { TEXT("weights"), EMcpParamKind::Array, true }, { TEXT("lodIndex"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_AnimationPhysics_84[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("skeletonPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_AnimationPhysics_85[] = { { TEXT("skeletonPath"), EMcpParamKind::String, false }, { TEXT("skeletalMeshPath"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false }, { TEXT("physicsAssetName"), EMcpParamKind::String, false }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("assignToMesh"), EMcpParamKind::Bool, false } };
inline const FMcpParamDecl P_AnimationPhysics_86[] = { { TEXT("actorName"), EMcpParamKind::String, true }, { TEXT("blendWeight"), EMcpParamKind::Number, false }, { TEXT("skeletonPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_AnimationPhysics_87[] = { { TEXT("sourceSkeleton"), EMcpParamKind::String, true }, { TEXT("targetSkeleton"), EMcpParamKind::String, true }, { TEXT("assets"), EMcpParamKind::Array, true }, { TEXT("retargetAssets"), EMcpParamKind::Array, true }, { TEXT("savePath"), EMcpParamKind::String, false }, { TEXT("suffix"), EMcpParamKind::String, false }, { TEXT("overwrite"), EMcpParamKind::Bool, false } };

inline const FMcpCallDecl GAnimationPhysics[] =
{
	{ TEXT("animation_physics"), TEXT("activate_ragdoll"), P_AnimationPhysics_0, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_aim_offset_sample"), P_AnimationPhysics_1, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_blend_node"), P_AnimationPhysics_2, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_blend_sample"), P_AnimationPhysics_3, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_bone"), P_AnimationPhysics_4, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_bone_track"), P_AnimationPhysics_5, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_cached_pose"), P_AnimationPhysics_6, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_layered_blend_per_bone"), P_AnimationPhysics_7, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_montage_notify"), P_AnimationPhysics_8, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_montage_section"), P_AnimationPhysics_9, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_montage_slot"), P_AnimationPhysics_10, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_notify"), P_AnimationPhysics_11, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_notify_state"), P_AnimationPhysics_12, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_physics_body"), P_AnimationPhysics_13, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_physics_constraint"), P_AnimationPhysics_14, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_slot_node"), P_AnimationPhysics_15, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_state"), P_AnimationPhysics_16, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_state_machine"), P_AnimationPhysics_17, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_sync_marker"), P_AnimationPhysics_18, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("add_transition"), P_AnimationPhysics_19, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("assign_cloth_asset_to_mesh"), P_AnimationPhysics_20, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("auto_skin_weights"), P_AnimationPhysics_21, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("bind_anim_notify"), P_AnimationPhysics_22, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("bind_cloth_to_skeletal_mesh"), P_AnimationPhysics_23, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("cleanup"), P_AnimationPhysics_24, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("configure_constraint_limits"), P_AnimationPhysics_25, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("configure_physics_body"), P_AnimationPhysics_26, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("configure_socket"), P_AnimationPhysics_27, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("configure_vehicle"), P_AnimationPhysics_28, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("copy_weights"), P_AnimationPhysics_29, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_aim_offset"), P_AnimationPhysics_30, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_anim_blueprint"), P_AnimationPhysics_31, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_animation_asset"), P_AnimationPhysics_32, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_animation_sequence"), P_AnimationPhysics_35, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_blend_space"), P_AnimationPhysics_36, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_blend_space_1d"), P_AnimationPhysics_37, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_blend_space_2d"), P_AnimationPhysics_38, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_blend_tree"), P_AnimationPhysics_39, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_control_rig"), P_AnimationPhysics_40, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_ik_retargeter"), P_AnimationPhysics_41, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_ik_rig"), P_AnimationPhysics_42, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_montage"), P_AnimationPhysics_43, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_morph_target"), P_AnimationPhysics_44, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_physics_asset"), P_AnimationPhysics_45, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_pose_library"), P_AnimationPhysics_46, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_procedural_anim"), P_AnimationPhysics_47, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_skeleton"), P_AnimationPhysics_48, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_socket"), P_AnimationPhysics_49, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_state_machine"), P_AnimationPhysics_50, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("create_virtual_bone"), P_AnimationPhysics_51, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("force_rebuild_blend_space"), P_AnimationPhysics_52, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("get_animation_info"), P_AnimationPhysics_53, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("get_skeleton_info"), P_AnimationPhysics_54, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("import_morph_targets"), P_AnimationPhysics_55, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("link_sections"), P_AnimationPhysics_56, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("list_bones"), P_AnimationPhysics_57, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("list_physics_bodies"), P_AnimationPhysics_58, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("list_sockets"), P_AnimationPhysics_59, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("mirror_weights"), P_AnimationPhysics_60, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("normalize_weights"), P_AnimationPhysics_61, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("play_montage"), P_AnimationPhysics_63, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("prune_weights"), P_AnimationPhysics_64, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("remove_bone"), P_AnimationPhysics_65, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("rename_bone"), P_AnimationPhysics_66, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_additive_settings"), P_AnimationPhysics_67, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_anim_graph_node_value"), P_AnimationPhysics_68, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_axis_settings"), P_AnimationPhysics_69, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_blend_in"), P_AnimationPhysics_70, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_blend_out"), P_AnimationPhysics_71, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_bone_key"), P_AnimationPhysics_72, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_bone_parent"), P_AnimationPhysics_73, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_bone_transform"), P_AnimationPhysics_74, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_curve_key"), P_AnimationPhysics_75, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_interpolation_settings"), P_AnimationPhysics_76, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_morph_target_deltas"), P_AnimationPhysics_77, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_retarget_chain_mapping"), P_AnimationPhysics_78, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_root_motion_settings"), P_AnimationPhysics_79, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_section_timing"), P_AnimationPhysics_80, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_sequence_length"), P_AnimationPhysics_81, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_transition_rules"), P_AnimationPhysics_82, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("set_vertex_weights"), P_AnimationPhysics_83, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("setup_ik"), P_AnimationPhysics_84, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("setup_physics_simulation"), P_AnimationPhysics_85, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("setup_ragdoll"), P_AnimationPhysics_86, EMcpCallFlags::None },
	{ TEXT("animation_physics"), TEXT("setup_retargeting"), P_AnimationPhysics_87, EMcpCallFlags::None },
};
}
