// Action declarations for manage_gas — the server's contract: which params
// each action reads, and which are required. Fleet-authored from handler
// source (three-witness cross-check, 2026-07-04), hand-maintained since:
// adding an action = adding its declaration here (the boot validation and
// tests/schema/action-decl-lint.ps1 enforce both directions).
// UnverifiedDecl = no reachable read path was attributable; validation skips
// those actions and the lint nags until someone verifies or removes them.
#pragma once

#include "MCP/McpCallRegistry.h"

namespace McpDecls
{
inline const FMcpParamDecl P_ManageGas_0[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, true }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("setPath"), EMcpParamKind::String, true }, { TEXT("abilityClass"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageGas_1[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("componentName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_2[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("taskType"), EMcpParamKind::String, true }, { TEXT("taskClassName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_3[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("attributeName"), EMcpParamKind::String, true }, { TEXT("baseValue"), EMcpParamKind::Number, false }, { TEXT("defaultValue"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageGas_4[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("cueTag"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageGas_5[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("calculationClass"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageGas_6[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("operation"), EMcpParamKind::String, false }, { TEXT("modifierOperation"), EMcpParamKind::String, false }, { TEXT("magnitude"), EMcpParamKind::Number, false }, { TEXT("modifierMagnitude"), EMcpParamKind::Number, false }, { TEXT("attribute"), EMcpParamKind::String, true }, { TEXT("setByCallerTag"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_7[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("tag"), EMcpParamKind::String, true }, { TEXT("tagName"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageGas_8[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("componentName"), EMcpParamKind::String, false }, { TEXT("replicationMode"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_9[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("triggerType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_10[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, true }, { TEXT("setPath"), EMcpParamKind::String, true }, { TEXT("setName"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_11[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_12[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_13[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_14[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("cueType"), EMcpParamKind::String, false }, { TEXT("cueTag"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_15[] = { { TEXT("name"), EMcpParamKind::String, true }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("durationType"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_16[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("actorName"), EMcpParamKind::String, false }, { TEXT("attribute"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageGas_17[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, false }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, true } };
inline const FMcpParamDecl P_ManageGas_18[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("cooldownEffectPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_19[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("costEffectPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_20[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("abilityTags"), EMcpParamKind::Array, false }, { TEXT("cancelAbilitiesWithTags"), EMcpParamKind::Array, false }, { TEXT("cancelAbilitiesWithTag"), EMcpParamKind::Array, false }, { TEXT("blockAbilitiesWithTags"), EMcpParamKind::Array, false }, { TEXT("blockAbilitiesWithTag"), EMcpParamKind::Array, false }, { TEXT("activationRequiredTags"), EMcpParamKind::Array, false }, { TEXT("activationBlockedTags"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageGas_21[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("targetingType"), EMcpParamKind::String, false }, { TEXT("targetingMode"), EMcpParamKind::String, false }, { TEXT("targetingRange"), EMcpParamKind::Number, false }, { TEXT("targetRange"), EMcpParamKind::Number, false }, { TEXT("aoeRadius"), EMcpParamKind::Number, false }, { TEXT("requiresLineOfSight"), EMcpParamKind::Bool, false }, { TEXT("targetingAngle"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageGas_22[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("activationPolicy"), EMcpParamKind::String, false }, { TEXT("policy"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_23[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("attributeName"), EMcpParamKind::String, true }, { TEXT("baseValue"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageGas_24[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("attributeName"), EMcpParamKind::String, true }, { TEXT("minValue"), EMcpParamKind::Number, false }, { TEXT("maxValue"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageGas_25[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("particleSystem"), EMcpParamKind::String, false }, { TEXT("particleSystemPath"), EMcpParamKind::String, false }, { TEXT("sound"), EMcpParamKind::String, false }, { TEXT("soundPath"), EMcpParamKind::String, false }, { TEXT("cameraShake"), EMcpParamKind::String, false }, { TEXT("cameraShakePath"), EMcpParamKind::String, false }, { TEXT("decalPath"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_26[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("durationType"), EMcpParamKind::String, false }, { TEXT("duration"), EMcpParamKind::Number, false }, { TEXT("period"), EMcpParamKind::Number, false } };
inline const FMcpParamDecl P_ManageGas_27[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("stackingType"), EMcpParamKind::String, false }, { TEXT("stackLimit"), EMcpParamKind::Number, false }, { TEXT("stackLimitCount"), EMcpParamKind::Number, false }, { TEXT("stackDurationRefreshPolicy"), EMcpParamKind::String, false }, { TEXT("stackPeriodResetPolicy"), EMcpParamKind::String, false }, { TEXT("stackExpirationPolicy"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_28[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("grantedTags"), EMcpParamKind::Array, false }, { TEXT("applicationRequiredTags"), EMcpParamKind::Array, false }, { TEXT("removalTags"), EMcpParamKind::Array, false }, { TEXT("immunityTags"), EMcpParamKind::Array, false } };
inline const FMcpParamDecl P_ManageGas_29[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("policy"), EMcpParamKind::String, false }, { TEXT("instancingPolicy"), EMcpParamKind::String, false } };
inline const FMcpParamDecl P_ManageGas_30[] = { { TEXT("name"), EMcpParamKind::String, false }, { TEXT("path"), EMcpParamKind::String, false }, { TEXT("blueprintPath"), EMcpParamKind::String, true }, { TEXT("attributeSetPath"), EMcpParamKind::String, false }, { TEXT("effectPath"), EMcpParamKind::String, false }, { TEXT("abilityPath"), EMcpParamKind::String, false }, { TEXT("cuePath"), EMcpParamKind::String, false }, { TEXT("assetPath"), EMcpParamKind::String, false }, { TEXT("modifierIndex"), EMcpParamKind::Number, false }, { TEXT("value"), EMcpParamKind::Number, false }, { TEXT("modifierMagnitude"), EMcpParamKind::Number, false }, { TEXT("magnitudeType"), EMcpParamKind::String, false }, { TEXT("magnitudeCalculationType"), EMcpParamKind::String, false }, { TEXT("setByCallerTag"), EMcpParamKind::String, false } };

inline const FMcpCallDecl GManageGas[] =
{
	{ TEXT("manage_gas"), TEXT("add_ability"), P_ManageGas_0, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_ability_system_component"), P_ManageGas_1, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_ability_task"), P_ManageGas_2, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_attribute"), P_ManageGas_3, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_effect_cue"), P_ManageGas_4, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_effect_execution_calculation"), P_ManageGas_5, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_effect_modifier"), P_ManageGas_6, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("add_tag_to_asset"), P_ManageGas_7, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("configure_asc"), P_ManageGas_8, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("configure_cue_trigger"), P_ManageGas_9, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("create_ability_set"), P_ManageGas_10, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("create_attribute_set"), P_ManageGas_11, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("create_execution_calculation"), P_ManageGas_12, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("create_gameplay_ability"), P_ManageGas_13, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("create_gameplay_cue_notify"), P_ManageGas_14, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("create_gameplay_effect"), P_ManageGas_15, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("get_attribute"), P_ManageGas_16, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("get_gas_info"), P_ManageGas_17, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_ability_cooldown"), P_ManageGas_18, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_ability_costs"), P_ManageGas_19, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_ability_tags"), P_ManageGas_20, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_ability_targeting"), P_ManageGas_21, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_activation_policy"), P_ManageGas_22, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_attribute_base_value"), P_ManageGas_23, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_attribute_clamping"), P_ManageGas_24, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_cue_effects"), P_ManageGas_25, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_effect_duration"), P_ManageGas_26, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_effect_stacking"), P_ManageGas_27, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_effect_tags"), P_ManageGas_28, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_instancing_policy"), P_ManageGas_29, EMcpCallFlags::None },
	{ TEXT("manage_gas"), TEXT("set_modifier_magnitude"), P_ManageGas_30, EMcpCallFlags::None },
};
}
