// McpTool_ManageAsset.cpp — manage_asset tool definition (45 actions)

#include "McpVersionCompatibility.h"
#include "MCP/McpToolDefinition.h"
#include "MCP/McpToolRegistry.h"
#include "MCP/McpSchemaBuilder.h"
#include "MCP/McpConsolidatedActionRouting.h"

class FMcpTool_ManageAsset : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_asset"); }

	FString GetDescription() const override
	{
		return TEXT("Create, import, duplicate, rename, delete assets. "
			"Edit Material graphs and instances. Analyze dependencies.");
	}

	FString GetCategory() const override { return TEXT("core"); }

	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		return FMcpSchemaBuilder()
				.StringEnum(TEXT("action"), McpConsolidatedActions::ManageAsset(),
					TEXT("Action to perform"))
			.String(TEXT("assetPath"), TEXT("Asset path (e.g., /Game/Path/Asset)."))
			.String(TEXT("propertyName"), TEXT("set_asset_property: name of the reflected UPROPERTY to write."))
			.Bool(TEXT("includeTransient"), TEXT("get_asset_properties: also dump transient (non-serialized) properties (default false)."))
			.String(TEXT("directory"), TEXT("list: directory to list (default /Game)."))
			.String(TEXT("reportType"), TEXT("generate_report: report kind, e.g. 'Summary' (default)."))
			.String(TEXT("outputPath"), TEXT("create_thumbnail/generate_report: file path (relative to project dir) to write output to. channel_extract: destination texture path."))
			.Bool(TEXT("recursive"), TEXT("list: recurse into subfolders (default true)."))
			.Array(TEXT("classNames"), TEXT(""))
			.Array(TEXT("packagePaths"), TEXT(""))
			.Bool(TEXT("recursivePaths"), TEXT(""))
			.Bool(TEXT("recursiveClasses"), TEXT(""))
			.Number(TEXT("limit"), TEXT(""))
			.Number(TEXT("offset"), TEXT(""))
			.String(TEXT("sourcePath"), TEXT("Source path for import/duplicate/rename/move (assetPath also accepted)."))
			.String(TEXT("destinationPath"), TEXT("Destination path for move/copy."))
			.Array(TEXT("assetPaths"), TEXT(""))
			.Array(TEXT("assets"), TEXT("generate_lods: alias for assetPaths."))
			.String(TEXT("landscapePath"), TEXT("generate_lods: landscape asset path (alternative to assetPath/assetPaths)."))
			.Number(TEXT("lodCount"), TEXT(""))
			.Number(TEXT("numLODs"), TEXT("generate_lods: alias for lodCount."))
			.FreeformObject(TEXT("reductionSettings"), TEXT("generate_lods: FMeshReductionSettings overrides applied to every generated LOD — percentTriangles/percentVertices (0-1, replace the progressive 50%/25%/... defaults), maxDeviation, pixelError, weldingThreshold, hardAngleThreshold, baseLODModel, recalculateNormals."))
			.String(TEXT("nodeName"), TEXT("Name identifier."))
			.String(TEXT("eventName"), TEXT("Name of the event."))
			.String(TEXT("memberClass"), TEXT(""))
			.Number(TEXT("posX"), TEXT(""))
			.Number(TEXT("posY"), TEXT(""))
			.String(TEXT("newName"), TEXT("rename/duplicate/move: new asset name, resolved into the source asset's folder (alternative to destinationPath)."))
			.Bool(TEXT("overwrite"), TEXT("Overwrite if the asset/file already exists."))
			.Bool(TEXT("save"), TEXT("Save the asset(s) after the operation."))
			.Bool(TEXT("fixupRedirectors"), TEXT(""))
			.String(TEXT("directoryPath"), TEXT("Path to a directory."))
			.String(TEXT("name"), TEXT("Name identifier."))
			.String(TEXT("path"), TEXT("Path to a directory."))
			.String(TEXT("parentMaterial"), TEXT("Material asset path."))
			.String(TEXT("materialDomain"), TEXT("create_material/set_material_domain: Surface|DeferredDecal|LightFunction|Volume|PostProcess|UI."))
			.String(TEXT("blendMode"), TEXT("create_material/set_blend_mode: Opaque|Masked|Translucent|Additive|Modulate|AlphaComposite|AlphaHoldout. combine_textures: Normal|Multiply|Screen|Overlay|Add."))
			.String(TEXT("shadingModel"), TEXT("create_material/set_shading_model: Unlit|DefaultLit|Subsurface|SubsurfaceProfile|PreintegratedSkin|ClearCoat|Hair|Cloth|Eye|TwoSidedFoliage|ThinTranslucent."))
			.Bool(TEXT("twoSided"), TEXT("create_material/set_two_sided: render both polygon faces."))
			.Bool(TEXT("exposeToLibrary"), TEXT("create_material_function: show in the Material Function Library picker (default true)."))
			.FreeformObject(TEXT("parameters"), TEXT(""))
			.Number(TEXT("width"), TEXT(""))
			.Number(TEXT("height"), TEXT(""))
			.String(TEXT("noiseType"), TEXT("create_noise_texture: Perlin (default) — FBM noise type."))
			.Number(TEXT("scale"), TEXT("create_noise_texture: noise frequency scale (default 1)."))
			.Number(TEXT("octaves"), TEXT("create_noise_texture: FBM octave count (default 4)."))
			.Number(TEXT("persistence"), TEXT("create_noise_texture: FBM amplitude falloff per octave (default 0.5)."))
			.Number(TEXT("lacunarity"), TEXT("create_noise_texture: FBM frequency growth per octave (default 2)."))
			.Number(TEXT("seed"), TEXT("create_noise_texture: noise seed (default 0)."))
			.Bool(TEXT("seamless"), TEXT("create_noise_texture: tile seamlessly (default false)."))
			.Bool(TEXT("hdr"), TEXT("create_noise_texture/create_gradient_texture: create a float/HDR texture (default false)."))
			.String(TEXT("gradientType"), TEXT("create_gradient_texture: Linear (default)|Radial|Angular."))
			.Number(TEXT("angle"), TEXT("create_gradient_texture: Linear gradient direction in degrees (default 0)."))
			.Number(TEXT("centerX"), TEXT("create_gradient_texture: Radial/Angular center U 0-1 (default 0.5)."))
			.Number(TEXT("centerY"), TEXT("create_gradient_texture: Radial/Angular center V 0-1 (default 0.5)."))
			.Number(TEXT("radius"), TEXT("create_gradient_texture: Radial falloff radius (default 0.5). blur: box-blur pixel radius 1-10 (default 2)."))
			.FreeformObject(TEXT("startColor"), TEXT("create_gradient_texture: {r,g,b,a} start color (default black)."))
			.FreeformObject(TEXT("endColor"), TEXT("create_gradient_texture: {r,g,b,a} end color (default white)."))
			.String(TEXT("patternType"), TEXT("create_pattern_texture: Checker (default)|Grid|Brick|Stripes|Dots."))
			.Number(TEXT("tilesX"), TEXT("create_pattern_texture: horizontal tile count (default 8)."))
			.Number(TEXT("tilesY"), TEXT("create_pattern_texture: vertical tile count (default 8)."))
			.Number(TEXT("lineWidth"), TEXT("create_pattern_texture: Grid/Brick line thickness 0-1 (default 0.02)."))
			.Number(TEXT("brickRatio"), TEXT("create_pattern_texture: Brick length-to-height ratio (default 2)."))
			.FreeformObject(TEXT("primaryColor"), TEXT("create_pattern_texture: {r,g,b,a} foreground color (default white)."))
			.FreeformObject(TEXT("secondaryColor"), TEXT("create_pattern_texture: {r,g,b,a} background color (default black)."))
			.String(TEXT("sourceTexture"), TEXT("create_normal_from_height: source height-map texture path."))
			.Number(TEXT("strength"), TEXT("create_normal_from_height: normal map intensity (default 1)."))
			.String(TEXT("algorithm"), TEXT("create_normal_from_height: Sobel (default) or finite-difference gradient method."))
			.Bool(TEXT("flipY"), TEXT("create_normal_from_height: flip the green channel (DirectX vs OpenGL normal convention)."))
			.String(TEXT("channelMode"), TEXT("create_normal_from_height: height source channel — luminance (default)|red|green|blue|alpha|average."))
			.String(TEXT("compressionSettings"), TEXT("set_compression_settings: TC_Default|TC_Normalmap|TC_Masks|TC_Grayscale|TC_Displacementmap|TC_VectorDisplacementmap|TC_HDR|TC_EditorIcon|TC_Alpha|TC_DistanceFieldFont|TC_HDR_Compressed|TC_BC7."))
			.String(TEXT("textureGroup"), TEXT("set_texture_group: e.g. World (default)|Character|Weapon|Vehicle|Cinematic|Effects|Skybox|UI|Lightmap|RenderTarget|Bokeh|Pixels2D."))
			.Number(TEXT("lodBias"), TEXT("set_lod_bias: additional texture LOD bias (default 0)."))
			.Bool(TEXT("virtualTextureStreaming"), TEXT("configure_virtual_texture: enable VT streaming (default false)."))
			.Number(TEXT("tileSize"), TEXT("configure_virtual_texture: VT tile size (default 128)."))
			.Number(TEXT("tileBorderSize"), TEXT("configure_virtual_texture: VT tile border size (default 4)."))
			.Bool(TEXT("neverStream"), TEXT("set_streaming_priority: disable mip streaming for this texture (default false)."))
			.Number(TEXT("newWidth"), TEXT("resize_texture: output width in pixels (default 512)."))
			.Number(TEXT("newHeight"), TEXT("resize_texture: output height in pixels (default 512)."))
			.String(TEXT("filterMethod"), TEXT("resize_texture: nearest|bilinear (default)|bicubic|lanczos."))
			.Bool(TEXT("inPlace"), TEXT("invert/desaturate/adjust_curves: modify the source texture instead of writing a new one (default true)."))
			.Bool(TEXT("invertAlpha"), TEXT("invert: also invert the alpha channel (default false)."))
			.String(TEXT("channel"), TEXT("invert: All (default)|Red|Green|Blue|Alpha. channel_extract: R (default)|G|B|A."))
			.Number(TEXT("amount"), TEXT("desaturate: blend amount 0-1 (default 1). sharpen: unsharp-mask amount 0-5 (default 1)."))
			.Number(TEXT("inBlack"), TEXT("adjust_levels: input black point 0-1 (default 0)."))
			.Number(TEXT("inWhite"), TEXT("adjust_levels: input white point 0-1 (default 1)."))
			.Number(TEXT("gamma"), TEXT("adjust_levels: gamma correction (default 1)."))
			.Number(TEXT("outBlack"), TEXT("adjust_levels: output black point 0-1 (default 0)."))
			.Number(TEXT("outWhite"), TEXT("adjust_levels: output white point 0-1 (default 1)."))
			.String(TEXT("redTexture"), TEXT("channel_pack: source texture for the output red channel."))
			.String(TEXT("greenTexture"), TEXT("channel_pack: source texture for the output green channel."))
			.String(TEXT("blueTexture"), TEXT("channel_pack: source texture for the output blue channel."))
			.String(TEXT("alphaTexture"), TEXT("channel_pack: source texture for the output alpha channel."))
			.String(TEXT("baseTexture"), TEXT("combine_textures: base texture path."))
			.String(TEXT("overlayTexture"), TEXT("combine_textures: overlay texture path (alias blendTexture)."))
			.String(TEXT("blendTexture"), TEXT("combine_textures: alias for overlayTexture."))
			.Number(TEXT("opacity"), TEXT("combine_textures: overlay blend opacity 0-1 (default 1)."))
			.Array(TEXT("input"), TEXT("adjust_curves: master curve input control points 0-1 (paired with output)."), TEXT("number"))
			.Array(TEXT("output"), TEXT("adjust_curves: master curve output control points 0-1 (paired with input)."), TEXT("number"))
			.Array(TEXT("inputR"), TEXT("adjust_curves: red-channel curve input control points."), TEXT("number"))
			.Array(TEXT("outputR"), TEXT("adjust_curves: red-channel curve output control points."), TEXT("number"))
			.Array(TEXT("inputG"), TEXT("adjust_curves: green-channel curve input control points."), TEXT("number"))
			.Array(TEXT("outputG"), TEXT("adjust_curves: green-channel curve output control points."), TEXT("number"))
			.Array(TEXT("inputB"), TEXT("adjust_curves: blue-channel curve input control points."), TEXT("number"))
			.Array(TEXT("outputB"), TEXT("adjust_curves: blue-channel curve output control points."), TEXT("number"))
			.Number(TEXT("sampleCount"), TEXT("create_ao_from_mesh: vertex samples per pixel (default 64)."))
			.Number(TEXT("rayDistance"), TEXT("create_ao_from_mesh: occlusion ray distance (default 100)."))
			.Number(TEXT("bias"), TEXT("create_ao_from_mesh: AO bias (default 0.01)."))
			.Number(TEXT("uvChannel"), TEXT("create_ao_from_mesh: source UV channel index (default 0)."))
			.String(TEXT("renderTargetPath"), TEXT("create_render_target: full asset path (alternative to name+path)."))
			.String(TEXT("format"), TEXT("import_data_table: 'csv' or 'json' (inferred from sourceText if omitted)."))
				.String(TEXT("rowStruct"), TEXT("create_data_table (required): row struct deriving from FTableRowBase — full path ('/Script/Module.Struct' or '/Game/.../UserStruct') or bare struct name."))
				.String(TEXT("rowStructPath"), TEXT("create_data_table: alias for rowStruct."))
				.String(TEXT("rowName"), TEXT("DataTable row CRUD: the row's key (FName)."))
				.FreeformObject(TEXT("rowData"), TEXT("DataTable add/edit row: JSON object of row-struct fields (partial edit merges)."))
				.String(TEXT("sourceText"), TEXT("import_data_table: the CSV or JSON text to import (replaces all rows)."))
				.String(TEXT("csv"), TEXT("import_data_table: alias for sourceText (CSV)."))
				.String(TEXT("json"), TEXT("import_data_table: alias for sourceText (JSON)."))
				.String(TEXT("content"), TEXT("import_data_table: alias for sourceText."))
				.String(TEXT("dataTablePath"), TEXT("DataTable row CRUD: alias for assetPath (the DataTable)."))
				.String(TEXT("tablePath"), TEXT("DataTable row CRUD: alias for assetPath (the DataTable)."))
			.String(TEXT("meshPath"), TEXT("Mesh asset path."))
			.Bool(TEXT("enableNanite"), TEXT("nanite_rebuild_mesh: enable Nanite virtualized geometry (default true)."))
			.Bool(TEXT("preserveArea"), TEXT("nanite_rebuild_mesh: preserve surface area during Nanite fallback mesh reduction (default true)."))
			.Number(TEXT("trianglePercent"), TEXT("nanite_rebuild_mesh: Nanite fallback mesh triangle percent 0-100 (default 100)."))
			.Number(TEXT("fallbackPercent"), TEXT("nanite_rebuild_mesh: Nanite fallback relative error percent 0-100 (default 0)."))
			.String(TEXT("tag"), TEXT("find_by_tag: tag key to match (set_tags metadata or asset-registry tag)."))
			.Bool(TEXT("searchAssets"), TEXT("find_by_tag: match asset registry/metadata tags (default true)."))
			.Bool(TEXT("searchActors"), TEXT("find_by_tag: match level-actor tags (default true)."))
			.Bool(TEXT("searchComponents"), TEXT("find_by_tag: match component tags (default false)."))
			.Number(TEXT("maxResults"), TEXT("find_by_tag: result cap (default 100, max 1000)."))
			.FreeformObject(TEXT("metadata"), TEXT(""))
			.String(TEXT("graphName"), TEXT("Name of the graph."))
			.String(TEXT("nodeType"), TEXT(""))
			.String(TEXT("operation"), TEXT("add_math_node: Add|Subtract|Multiply|Divide|Lerp|Clamp|Power|Frac|OneMinus|Append."))
			.String(TEXT("nodeId"), TEXT("ID of the node."))
			.Array(TEXT("nodeIds"), TEXT("delete_node: batch-delete multiple node IDs (alternative to nodeId)."))
			.String(TEXT("sourceNodeId"), TEXT("ID of the source node."))
			.String(TEXT("targetNodeId"), TEXT("ID of the target node."))
			.String(TEXT("sourcePin"), TEXT("connect_nodes: named output pin on the source node (e.g. an MF call output); defaults to output 0."))
			.String(TEXT("startNodeId"), TEXT("get_node_chain: node ID to trace the signal path from."))
			.String(TEXT("endNodeId"), TEXT("get_node_chain: node ID (or \"Main\") to trace the signal path to."))
			.String(TEXT("endPin"), TEXT("get_node_chain: named material main-pin to trace to, e.g. 'BaseColor' (alternative to endNodeId)."))
			.String(TEXT("inputName"), TEXT("Name of the pin."))
			.String(TEXT("parameterName"), TEXT("Name of the parameter."))
			.String(TEXT("group"), TEXT("add_scalar_parameter/add_vector_parameter/add_static_switch_parameter: UI group name."))
			.FreeformObject(TEXT("value"), TEXT("Generic value (any type)."))
			.Number(TEXT("x"), TEXT(""))
			.Number(TEXT("y"), TEXT(""))
			.String(TEXT("comment"), TEXT(""))
			.String(TEXT("parentNodeId"), TEXT("ID of the node."))
			.String(TEXT("childNodeId"), TEXT("ID of the node."))
			.Number(TEXT("maxDepth"), TEXT(""))
			.Number(TEXT("depth"), TEXT("list: recursion depth filter relative to the queried path. get_node_connections: BFS hop limit (default 1; -1 unlimited)."))
			.String(TEXT("direction"), TEXT("get_node_connections: inputs|outputs|both (default both)."))
			.Bool(TEXT("upstream"), TEXT("get_node_connections: walk backward to all sources (overrides direction/depth)."))
			.Bool(TEXT("downstream"), TEXT("get_node_connections: walk forward to all consumers (overrides direction/depth)."))
			.Bool(TEXT("orphansOnly"), TEXT("get_connected_subgraph: return all nodes not connected to any output, ignoring nodeId."))
			.String(TEXT("prefix"), TEXT(""))
			.String(TEXT("suffix"), TEXT(""))
			.String(TEXT("searchText"), TEXT(""))
			.String(TEXT("replaceText"), TEXT(""))
			.String(TEXT("pattern"), TEXT("bulk_delete: substring filter applied to matching asset names when deleting by folderPath."))
			.Array(TEXT("paths"), TEXT(""))
			.String(TEXT("description"), TEXT(""))
			.String(TEXT("code"), TEXT("add_custom_expression/update_custom_expression: HLSL source code body."))
			.String(TEXT("outputType"), TEXT("add_custom_expression/update_custom_expression: Float1|Float2|Float3|Float4|MaterialAttributes (default Float1)."))
			.Bool(TEXT("checkoutFiles"), TEXT(""))
			.Bool(TEXT("showConfirmation"), TEXT(""))
			.String(TEXT("pinName"), TEXT("Name of the pin."))
			.String(TEXT("materialPath"), TEXT("Material asset path."))
			.String(TEXT("functionPath"), TEXT("use_material_function: material function asset path to call."))
			.String(TEXT("texturePath"), TEXT("Texture asset path."))
			.String(TEXT("samplerType"), TEXT("add_texture_sample: Color|LinearColor|Normal|Masks|Alpha (default Color)."))
			.Number(TEXT("coordinateIndex"), TEXT(""))
			.Number(TEXT("uTiling"), TEXT("add_texture_coordinate: horizontal tiling (default 1)."))
			.Number(TEXT("vTiling"), TEXT("add_texture_coordinate: vertical tiling (default 1)."))
			.String(TEXT("parameterType"), TEXT(""))
			.String(TEXT("filter"), TEXT("get_material_info: what to include — 'parameters'|'expressions'|'connections'|'all' (default all)."))
			.String(TEXT("inputType"), TEXT("add_function_input/add_function_output: Float1|Float2|Float3|Float4|Texture2D|TextureCube|Bool|MaterialAttributes."))
			.Array(TEXT("tags"), TEXT(""))
			.String(TEXT("layerName"), TEXT("add_landscape_layer: landscape layer name."))
			.Number(TEXT("hardness"), TEXT("add_landscape_layer: layer info hardness 0-1 (default 0.5)."))
			.String(TEXT("physicalMaterialPath"), TEXT("add_landscape_layer: optional physical material asset path."))
			.Bool(TEXT("noWeightBlend"), TEXT("add_landscape_layer: disable weight-blending for this layer (default false)."))
			.ArrayOfObjects(TEXT("layers"), TEXT("configure_layer_blend: layers to add, e.g. [{\"name\":\"Rock\",\"blendType\":\"...\"}]."))
			.String(TEXT("folderPath"), TEXT("Path to a directory."))
			.String(TEXT("type"), TEXT(""))
			.FreeformObject(TEXT("defaultValue"), TEXT("Generic value (any type)."))
			.FreeformObject(TEXT("luminanceFactors"), TEXT("add_desaturation: optional {r,g,b} luminance weights (default 0.3/0.59/0.11)."))
			.String(TEXT("expressionIndex"), TEXT("ID of the node."))
			.ArrayOfObjects(TEXT("inputs"), TEXT("add_custom_expression/update_custom_expression: named HLSL input pins, e.g. [{\"name\":\"UV\"}]. Each name becomes a connect_nodes inputName."))
			.ArrayOfObjects(TEXT("additionalOutputs"), TEXT("add_custom_expression/update_custom_expression: extra named outputs beyond the primary return, e.g. [{\"name\":\"Mask\",\"type\":\"Float1\"}]."))
			.Number(TEXT("r"), TEXT("set_node_value: red/X channel of a Constant2/3/4Vector or VectorParameter default."))
			.Number(TEXT("g"), TEXT("set_node_value: green/Y channel."))
			.Number(TEXT("b"), TEXT("set_node_value: blue/Z channel."))
			.Number(TEXT("a"), TEXT("set_node_value: alpha/W channel (Constant4Vector / VectorParameter)."))
			.Number(TEXT("constA"), TEXT("set_node_value: ConstA default of an arithmetic node (Add/Multiply/…) when input A is unconnected."))
			.Number(TEXT("constB"), TEXT("set_node_value: ConstB default of an arithmetic node when input B is unconnected."))
			.Bool(TEXT("waitForShaders"), TEXT("compile_material: block on the async shader workers so backend (not just translation) errors are reported. Slower; off by default."))
			.Required({TEXT("action")})
			.Build();
	}
};

MCP_REGISTER_TOOL(FMcpTool_ManageAsset);
